server:
  port: 0

spring:
  application:
    name: product-service

eureka:
  client:
    service-url:
      defaultZones: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
